### PR TITLE
Fixup the interaction of CAbstractStruct, abstract types, and polymorphic equalities

### LINKED ISSUE #245: krml crashes in Monomorphization.ml
I'm using 70084646b6f5cf01d58a2ed1c0e69d34829ba480

Here's a repro:

Abstract.fsti:

```
module Abstract

[@@CAbstractStruct]
val t : eqtype

val mk_t (_:unit) : t
```

Test.fsti:

```
module Test

val nothing : unit -> bool
```

Test.fst:

```
module Test
open Abstract

type pair = {
  fst : t;
  snd : bool
}


let test (x y:pair) : bool = x = y

let nothing() =
  let x = mk_t () in
  test ({fst=x; snd=true}) ({fst=x;snd=false})
```

I observe the following:

```
krml -bundle Test=Abstract prims.krml FStar_Pervasives_Native.krml FStar_Pervasives.krml Abstract.krml Test.krml
✔ [Monomorphization] ⏱️ 9ms
Fatal error: exception File "src/Monomorphization.ml", line 502, characters 16-22: Assertion failed
```

cc @tahina-pro @arvinda

### PR DESCRIPTION
**Pull request by msprotz**
This fixes #245

Note: the original test was ill-formed, in that it was declaring a C abstract struct but yet declaring a function that had the ability to *construct* values of the struct type without a pointer.

I had to add some custom hand-written files to make the test work -- I assume this is representative of your scenario.

Please confirm this solves the problem you were encountering, thanks!

### CODE REVIEW

**Comment by nikswamy** [comment]
#245 was synthetic test case on which I observed krml crashing. If this fixes the crash, then that's good.

Does this PR also address #247? that's the case that I'm really interested in and is more representative of the issue I was observing in my full scenario.

**Comment by msprotz** [comment]
#247 is coming up next -- my hunch was that I had at least to clean this up before tackling the core visibility issue

**Comment by nikswamy** [comment]
I tried out this branch on my sample code and it indeed produces a smaller, better looking interface.

However, I did also notice that the issue I reported in #245 is actually also representative of my application. I have declared a type `t` as CAbstractStruct. And then have a function in my external API whose signature is like `t -> unit`. And krml extracts this to something like this header file:

```
typedef struct t_s t

void f(t x)
```

Even though `f` receives a `t` argument rather than a `t *` argument.

Is there a way for krml to detect this situation and emit a warning such as "Type t is declared as a CAbstractStruct but its values are exchanged on the public API without a pointer indirection" ... or something like that?

As it stands now, because of this misuse of CAbstractStruct, it is possible for F* + krml to produce code without any warnings that will fail to compile in C.

**Comment by msprotz** [comment]
Correct, this has always been an attribute with no actual check behind the scenes that it is being used properly. I agree that it would be nice for krml to warn about this, but this should be a separate issue and discussion. In the meanwhile, I take it that this solves the crash and I'll merge it as soon as I get an Everest green. Thanks for checking!

**Pull request merged**
